import { PaginatedResponse } from ".."

export interface MovieSearchResult {
  adult: boolean
  backdrop_path: string | null
  genre_ids: number[]
  id: number
  original_language: string
  original_title: string
  overview: string
  popularity: number
  poster_path: string
  release_date: string
  title: string
  video: boolean
  vote_average: number
  vote_count: number
}

export type MoviesSearchResults = PaginatedResponse<MovieSearchResult>

export const mockMoviesSearchResults: MoviesSearchResults = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
      genre_ids: [878, 28, 12, 10749],
      id: 624860,
      original_language: "en",
      original_title: "The Matrix Resurrections",
      overview:
        "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
      popularity: 3828.374,
      poster_path: "/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
      release_date: "2021-12-16",
      title: "The Matrix Resurrections",
      video: false,
      vote_average: 6.9,
      vote_count: 2451,
    },
    {
      adult: false,
      backdrop_path: "/ncEsesgOJDNrTUED89hYbA117wo.jpg",
      genre_ids: [28, 878],
      id: 603,
      original_language: "en",
      original_title: "The Matrix",
      overview:
        "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
      popularity: 166.407,
      poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
      release_date: "1999-03-30",
      title: "The Matrix",
      video: false,
      vote_average: 8.2,
      vote_count: 20915,
    },
    {
      adult: false,
      backdrop_path: "/tva2OlLELCagFynFibcefhn2D9i.jpg",
      genre_ids: [12, 28, 53, 878],
      id: 604,
      original_language: "en",
      original_title: "The Matrix Reloaded",
      overview:
        "Six months after the events depicted in The Matrix, Neo has proved to be a good omen for the free humans, as more and more humans are being freed from the matrix and brought to Zion, the one and only stronghold of the Resistance.  Neo himself has discovered his superpowers including super speed, ability to see the codes of the things inside the matrix and a certain degree of pre-cognition. But a nasty piece of news hits the human resistance: 250,000 machine sentinels are digging to Zion and would reach them in 72 hours. As Zion prepares for the ultimate war, Neo, Morpheus and Trinity are advised by the Oracle to find the Keymaker who would help them reach the Source.  Meanwhile Neo's recurrent dreams depicting Trinity's death have got him worried and as if it was not enough, Agent Smith has somehow escaped deletion, has become more powerful than before and has fixed Neo as his next target.",
      popularity: 118.851,
      poster_path: "/9TGHDvWrqKBzwDxDodHYXEmOE6J.jpg",
      release_date: "2003-05-15",
      title: "The Matrix Reloaded",
      video: false,
      vote_average: 7,
      vote_count: 8707,
    },
    {
      adult: false,
      backdrop_path: "/kJYPag1YrA4PsXIftFdq3QEaanV.jpg",
      genre_ids: [12, 28, 53, 878],
      id: 605,
      original_language: "en",
      original_title: "The Matrix Revolutions",
      overview:
        "The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.",
      popularity: 115.376,
      poster_path: "/fgm8OZ7o4G1G1I9EeGcb85Noe6L.jpg",
      release_date: "2003-11-05",
      title: "The Matrix Revolutions",
      video: false,
      vote_average: 6.7,
      vote_count: 7806,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [878],
      id: 51767,
      original_language: "en",
      original_title: "Sexual Matrix",
      overview:
        "A professor designing a machine designed to meet the naughtiest fantasies. In order to perfect the discovery, he performed tests on various subjects, aided by his very appealing assistant.",
      popularity: 29.851,
      poster_path: "/vmhBIPKyYCWlp2PrIIc6EXZlP9Z.jpg",
      release_date: "2000-04-01",
      title: "Sexual Matrix",
      video: false,
      vote_average: 7.2,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: "/lBdXACywnLwKUZmZkZ87djDQBeV.jpg",
      genre_ids: [99],
      id: 14543,
      original_language: "en",
      original_title: "The Matrix Revisited",
      overview:
        "The film goes behind the scenes of the 1999 sci-fi movie The Matrix.",
      popularity: 34.073,
      poster_path: "/8yxSztoc5sqZiGuKcFuVOh65B6Y.jpg",
      release_date: "2001-11-19",
      title: "The Matrix Revisited",
      video: false,
      vote_average: 6.9,
      vote_count: 153,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99, 878],
      id: 221495,
      original_language: "en",
      original_title: "The Matrix Recalibrated",
      overview:
        "The making of Matrix Revolutions, The (2003) is briefly touched on here in this documentary. Interviews with various cast and crew members inform us how they were affected by the deaths of Gloria Foster and Aaliyah, and also delve into the making of the visual effects that takes up a lot of screen time. Written by Rhyl Donnelly",
      popularity: 24.675,
      poster_path: "/gRni1Q651AZPnLqZczmahiIxG0s.jpg",
      release_date: "2004-04-06",
      title: "The Matrix Recalibrated",
      video: true,
      vote_average: 6.6,
      vote_count: 34,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 591955,
      original_language: "en",
      original_title: "The Matrix Reloaded Revisited",
      overview:
        "The making of The Matrix Reloaded:  Go to the middle movie's furthest reaches via five documentary paths revealing 21 featurettes.",
      popularity: 24.214,
      poster_path: "/gb7C4oRzYWXWCuZMR1cwtHa53Pz.jpg",
      release_date: "2004-12-07",
      title: "The Matrix Reloaded Revisited",
      video: false,
      vote_average: 7.2,
      vote_count: 15,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99, 28, 878],
      id: 684428,
      original_language: "en",
      original_title: "The Matrix: What Is Bullet-Time?",
      overview:
        'Special Effects wizard John Gaeta demonstrates how the "Bullet-Time" effects were created for the film Matrix, The (1999).',
      popularity: 30.998,
      poster_path: "/hSTervHaROcTd8Ir3DPfepN80dL.jpg",
      release_date: "1999-09-21",
      title: "The Matrix: What Is Bullet-Time?",
      video: false,
      vote_average: 5.2,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 99, 878],
      id: 684731,
      original_language: "en",
      original_title: "The Matrix Reloaded: Pre-Load",
      overview:
        "This making-of piece offers the standard mix of movie snippets, behind the scenes materials, and interviews from cast and crew on the making of the film.",
      popularity: 21.179,
      poster_path: "/zkpzfTyF7BjadH1PZKlC6kueWXf.jpg",
      release_date: "2003-10-14",
      title: "The Matrix Reloaded: Pre-Load",
      video: false,
      vote_average: 6.3,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: "/b3toMttpZ0cFeYMgLeL042uJJpi.jpg",
      genre_ids: [99, 28, 878],
      id: 684735,
      original_language: "en",
      original_title: "Making 'Enter the Matrix'",
      overview:
        "A look at Enter the Matrix: The game's story picks up just before The Matrix Reloaded and runs parallel to that of the film. Bend the rules of the Matrix with martial arts, pilot the fastest hovercraft in the fleet, or just fight with lots of guns.",
      popularity: 11.259,
      poster_path: "/zQbJkJkzpB8EthEJ3r2Y6A2kkP6.jpg",
      release_date: "2003-10-14",
      title: "Making 'Enter the Matrix'",
      video: false,
      vote_average: 3.8,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [9648, 878],
      id: 129399,
      original_language: "en",
      original_title: "Time Matrix",
      overview:
        "In the near future, police detective Richard Manning is investigating the most difficult case of his career – the seemingly impossible locked room murder of a wealthy property investor. The more Richard investigates, the more complex the case seems to become. He soon realizes his own future and survival depend on him solving everything – and quickly.",
      popularity: 7.629,
      poster_path: "/3pT6TI22UbIckjoMu05tO2mkLYW.jpg",
      release_date: "2013-01-01",
      title: "Time Matrix",
      video: false,
      vote_average: 4.3,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: "/5nxDn3mrdmeUHJOZi1Wfqya8Vji.jpg",
      genre_ids: [99],
      id: 696109,
      original_language: "en",
      original_title: "A Glitch in the Matrix",
      overview:
        "Are we in fact living in a simulation? This is the question postulated, wrestled with, and ultimately argued for through archival footage, compelling interviews with real people shrouded in digital avatars, and a collection of cases from some of our most iconoclastic figures in contemporary culture.",
      popularity: 9.014,
      poster_path: "/bn0BLVadmvzq6MmJ0n97MLxGpNQ.jpg",
      release_date: "2021-02-05",
      title: "A Glitch in the Matrix",
      video: false,
      vote_average: 5.4,
      vote_count: 19,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 503880,
      original_language: "en",
      original_title: "The Matrix Revolutions Revisited",
      overview:
        "The making of The Matrix Revolutions:\r The cataclysmic final confrontation chronicled through six documentary pods revealing 28 featurettes",
      popularity: 9.988,
      poster_path: "/61ASnmqvzpuz9VEfFElo3e2nIft.jpg",
      release_date: "2004-12-07",
      title: "The Matrix Revolutions Revisited",
      video: false,
      vote_average: 7.8,
      vote_count: 11,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 274866,
      original_language: "en",
      original_title: "The Roots of the Matrix",
      overview:
        "Disc 8 of 10 of 'The Matrix: Ultimate Edition': Probe the philosophical and technological inspirations of The Matrix Trilogy through two insightful documentaries:  - Return to Source: Philosophy &amp; The Matrix documentary – Scholars, philosophers and theorists deconstruct the intellectual underpinnings of the trilogy  - The Hard Problem: The Science Behind the Fiction documentary – Is the notion of a real Matrix plausible? An investigation of the technologies that inspire the metaphor of the Matrix.",
      popularity: 11.327,
      poster_path: "/qmOtnpPihV3Wj6ukpiNIgzo4Ax7.jpg",
      release_date: "2004-12-07",
      title: "The Roots of the Matrix",
      video: false,
      vote_average: 7,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99, 28, 878],
      id: 684729,
      original_language: "en",
      original_title: "The Matrix Reloaded: Car Chase",
      overview:
        "This thirty-minute documentary follows the Wachowski sisters and the film's crew through production on the film's famed highway chase sequence. We get interviews with the visual effects supervisors, the stunt coordinators and even are taken through aspects of pre-production and planning for the scene. Then the documentary moves into production, the scariest aspect of which is certainly Carrie Anne-Moss trying to learn to ride a motorcycle good enough to do so safely without helmet for the scene. We also watch as the stretch of freeway used in the film is being built.",
      popularity: 10.423,
      poster_path: "/zkpzfTyF7BjadH1PZKlC6kueWXf.jpg",
      release_date: "2004-12-07",
      title: "The Matrix Reloaded: Car Chase",
      video: false,
      vote_average: 6,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16, 878, 53],
      id: 33322,
      original_language: "ja",
      original_title: "アミテージ・ザ・サード POLY-MATRIX",
      overview:
        "Ross Sylibus is assigned to a police unit on a Martian colony, to find that women are being murdered by a psychotic named D'anclaude. He is assigned a very unorthodox partner named Naomi Armitage, who seems to have links to the victims. To stir things up more, every victim is found to be an illegally made third-generation android.",
      popularity: 6.266,
      poster_path: "/7sUCRdjGe7VggDCGIHywfguYdAK.jpg",
      release_date: "1996-06-25",
      title: "Armitage III: Poly Matrix",
      video: false,
      vote_average: 6.4,
      vote_count: 36,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [53, 28, 16, 878, 12],
      id: 21769,
      original_language: "ja",
      original_title: "アミテージ・ザ・サード DUAL-MATRIX",
      overview:
        "Naomi Armitage and Ross Sylibus have changed their names and live with their daughter Yoko as a happy and normal family on Mars — until an android riot breaks out at an anti-matter plant on Earth.",
      popularity: 2.704,
      poster_path: "/p5nd9VPKxpow5MFAQfZy2DEatPI.jpg",
      release_date: "2002-03-22",
      title: "Armitage: Dual Matrix",
      video: false,
      vote_average: 6.4,
      vote_count: 33,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 99, 878],
      id: 684431,
      original_language: "en",
      original_title: "Making 'The Matrix'",
      overview:
        "A promotional making-of documentary for the film Matrix, The (1999) that devotes its time to explaining the digital and practical effects contained in the film. This is very interesting, seeing as how they're giving away the cinematic secrets that they created solely for the this movie, that have now been spoofed and referenced in countless other films.",
      popularity: 1.676,
      poster_path: "/m2yIfRJYwpCgHON1Ig1pNKMWTxp.jpg",
      release_date: "1999-09-21",
      title: "Making 'The Matrix'",
      video: false,
      vote_average: 6.7,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 217056,
      original_language: "en",
      original_title: "Matrix of Evil",
      overview:
        "is a dynamic 2 hour video featuring some of the most informed minds in the world today who expose the latest revelations of the New World Order's agenda in shocking detail.",
      popularity: 2.17,
      poster_path: "/A2kExZKGqluSZMO4BiilAfs2axG.jpg",
      release_date: "2003-01-01",
      title: "Matrix of Evil",
      video: true,
      vote_average: 6.8,
      vote_count: 3,
    },
  ],
  total_pages: 4,
  total_results: 76,
}
