export interface KnownForMovie {
  media_type: "movie"
  adult: boolean
  backdrop_path: string
  genre_ids: number[]
  id: number
  original_language: string
  original_title: string
  overview: string
  poster_path: string
  release_date: string
  title: string
  video: boolean
  vote_average: number
  vote_count: number
}

export interface KnownForTvShow {
  media_type: "tv"
  backdrop_path: string
  first_air_date: string
  genre_ids: number[]
  id: number
  name: string
  origin_country: string[]
  original_language: string
  original_name: string
  overview: string
  poster_path: string
  vote_average: number
  vote_count: number
}

export interface Result {
  adult: boolean
  gender: number
  id: number
  known_for: Array<KnownForMovie | KnownForTvShow>
  known_for_department: string
  name: string
  popularity: number
  profile_path: string
}

export interface PopularPeople {
  page: number
  results: Result[]
  total_pages: number
  total_results: number
}

export const mockPopularPeople: PopularPeople = {
  page: 1,
  results: [
    {
      adult: false,
      gender: 1,
      id: 224513,
      known_for: [
        {
          adult: false,
          backdrop_path: "/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg",
          genre_ids: [878, 18],
          id: 335984,
          media_type: "movie",
          original_language: "en",
          original_title: "Blade Runner 2049",
          overview:
            "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
          poster_path: "/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
          release_date: "2017-10-04",
          title: "Blade Runner 2049",
          video: false,
          vote_average: 7.5,
          vote_count: 10359,
        },
        {
          adult: false,
          backdrop_path: "/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg",
          genre_ids: [35, 18, 80, 9648],
          id: 546554,
          media_type: "movie",
          original_language: "en",
          original_title: "Knives Out",
          overview:
            "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
          poster_path: "/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
          release_date: "2019-11-27",
          title: "Knives Out",
          video: false,
          vote_average: 7.9,
          vote_count: 8373,
        },
        {
          adult: false,
          backdrop_path: "/oNoprEND25zXR6Fns8cIZUkuoMc.jpg",
          genre_ids: [35, 80, 18],
          id: 308266,
          media_type: "movie",
          original_language: "en",
          original_title: "War Dogs",
          overview:
            "Based on the true story of two young men, David Packouz and Efraim Diveroli, who won a $300 million contract from the Pentagon to arm America's allies in Afghanistan.",
          poster_path: "/mDcPRjZC1bb6LavFU3gwsWdVfCM.jpg",
          release_date: "2016-08-17",
          title: "War Dogs",
          video: false,
          vote_average: 6.9,
          vote_count: 3736,
        },
      ],
      known_for_department: "Acting",
      name: "Ana de Armas",
      popularity: 161.892,
      profile_path: "/14uxt0jH28J9zn4vNQNTae3Bmr7.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 1136406,
      known_for: [
        {
          adult: false,
          backdrop_path: "/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
          genre_ids: [12, 28, 878],
          id: 299536,
          media_type: "movie",
          original_language: "en",
          original_title: "Avengers: Infinity War",
          overview:
            "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
          poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
          release_date: "2018-04-25",
          title: "Avengers: Infinity War",
          video: false,
          vote_average: 8.3,
          vote_count: 23713,
        },
        {
          adult: false,
          backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
          genre_ids: [12, 878, 28],
          id: 299534,
          media_type: "movie",
          original_language: "en",
          original_title: "Avengers: Endgame",
          overview:
            "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
          poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
          release_date: "2019-04-24",
          title: "Avengers: Endgame",
          video: false,
          vote_average: 8.3,
          vote_count: 20181,
        },
        {
          adult: false,
          backdrop_path: "/7FWlcZq3r6525LWOcvO9kNWurN1.jpg",
          genre_ids: [12, 28, 878],
          id: 271110,
          media_type: "movie",
          original_language: "en",
          original_title: "Captain America: Civil War",
          overview:
            "Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.",
          poster_path: "/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
          release_date: "2016-04-27",
          title: "Captain America: Civil War",
          video: false,
          vote_average: 7.4,
          vote_count: 19250,
        },
      ],
      known_for_department: "Acting",
      name: "Tom Holland",
      popularity: 156.615,
      profile_path: "/2qhIDp44cAqP2clOgt2afQI07X8.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 169337,
      known_for: [
        {
          backdrop_path: "/gIApbx2ffXVhJb2D4tiEx2b06nl.jpg",
          first_air_date: "2005-03-27",
          genre_ids: [18],
          id: 1416,
          media_type: "tv",
          name: "Grey's Anatomy",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Grey's Anatomy",
          overview:
            "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
          poster_path: "/zPIug5giU8oug6Xes5K1sTfQJxY.jpg",
          vote_average: 8.2,
          vote_count: 7445,
        },
        {
          backdrop_path: "/hiK4qc0tZijQ9KNUnBIS1k4tdMJ.jpg",
          first_air_date: "2004-11-16",
          genre_ids: [18, 35, 9648],
          id: 1408,
          media_type: "tv",
          name: "House",
          origin_country: ["US"],
          original_language: "en",
          original_name: "House",
          overview:
            "Dr. Gregory House, a drug-addicted, unconventional, misanthropic medical genius, leads a team of diagnosticians at the fictional Princeton–Plainsboro Teaching Hospital in New Jersey.",
          poster_path: "/lkvhReTBZ2Ksl0Dl5Oplsf6UYkF.jpg",
          vote_average: 8.6,
          vote_count: 4326,
        },
        {
          adult: false,
          backdrop_path: "/sNsANx5OxYifdcW7UXbyL9GoMCO.jpg",
          genre_ids: [35, 10749],
          id: 32856,
          media_type: "movie",
          original_language: "en",
          original_title: "Valentine's Day",
          overview:
            "More than a dozen Angelenos navigate Valentine's Day from early morning until midnight. Three couples awake together, but each relationship will sputter. A grade-school boy wants flowers for his first true love. Two high school seniors plan first-time sex at noon. A TV sports reporter gets the assignment to find romance in LA. A star quarterback contemplates his future. Two strangers meet on a plane. Grandparents, together for years, face a crisis. An 'I Hate Valentine's Day' dinner beckons the lonely and the lied to.",
          poster_path: "/qOTcfD2DdnOTmhH0r1TOE09VvNh.jpg",
          release_date: "2010-02-10",
          title: "Valentine's Day",
          video: false,
          vote_average: 5.9,
          vote_count: 2608,
        },
      ],
      known_for_department: "Acting",
      name: "Katherine LaNasa",
      popularity: 141.949,
      profile_path: "/a1T5Smn7sCEtV8NHvTa5WaxgOML.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 15555,
      known_for: [
        {
          adult: false,
          backdrop_path: "/mfJepkInUbiZ0mFXFhDNz8ko6Zr.jpg",
          genre_ids: [18, 9648, 878],
          id: 1124,
          media_type: "movie",
          original_language: "en",
          original_title: "The Prestige",
          overview:
            "A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy -- full of obsession, deceit and jealousy with dangerous and deadly consequences.",
          poster_path: "/bdN3gXuIZYaJP7ftKK2sU0nPtEA.jpg",
          release_date: "2006-10-19",
          title: "The Prestige",
          video: false,
          vote_average: 8.2,
          vote_count: 12613,
        },
        {
          adult: false,
          backdrop_path: "/4bAwGmE9Sl4FeXoHWVWLXkURHbe.jpg",
          genre_ids: [28, 53, 878],
          id: 59967,
          media_type: "movie",
          original_language: "en",
          original_title: "Looper",
          overview:
            "In the futuristic action thriller Looper, time travel will be invented but it will be illegal and only available on the black market. When the mob wants to get rid of someone, they will send their target 30 years into the past where a looper, a hired gun, like Joe is waiting to mop up. Joe is getting rich and life is good until the day the mob decides to close the loop, sending back Joe's future self for assassination.",
          poster_path: "/sNjL6SqErDBE8OUZlrDLkexfsCj.jpg",
          release_date: "2012-09-26",
          title: "Looper",
          video: false,
          vote_average: 6.8,
          vote_count: 8685,
        },
        {
          backdrop_path: "/hiK4qc0tZijQ9KNUnBIS1k4tdMJ.jpg",
          first_air_date: "2004-11-16",
          genre_ids: [18, 35, 9648],
          id: 1408,
          media_type: "tv",
          name: "House",
          origin_country: ["US"],
          original_language: "en",
          original_name: "House",
          overview:
            "Dr. Gregory House, a drug-addicted, unconventional, misanthropic medical genius, leads a team of diagnosticians at the fictional Princeton–Plainsboro Teaching Hospital in New Jersey.",
          poster_path: "/lkvhReTBZ2Ksl0Dl5Oplsf6UYkF.jpg",
          vote_average: 8.6,
          vote_count: 4333,
        },
      ],
      known_for_department: "Acting",
      name: "Piper Perabo",
      popularity: 93.899,
      profile_path: "/aP9QqLm4JZxLwp2CiUbEh5zrpVI.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 543990,
      known_for: [
        {
          adult: false,
          backdrop_path: "/oxB5Og9FEHRIBo6eTN6pvobYC6G.jpg",
          genre_ids: [12, 14, 10751],
          id: 32657,
          media_type: "movie",
          original_language: "en",
          original_title: "Percy Jackson & the Olympians: The Lightning Thief",
          overview:
            "Accident prone teenager, Percy discovers he's actually a demi-God, the son of Poseidon, and he is needed when Zeus' lightning is stolen. Percy must master his new found skills in order to prevent a war between the Gods that could devastate the entire world.",
          poster_path: "/vayx5t1cYCpBGV9ylTGn0Sr9rA2.jpg",
          release_date: "2010-02-01",
          title: "Percy Jackson & the Olympians: The Lightning Thief",
          video: false,
          vote_average: 6.2,
          vote_count: 6134,
        },
        {
          adult: false,
          backdrop_path: "/q8hENt2WsQAAtG9NJNJxMpNOlOm.jpg",
          genre_ids: [35, 18, 10751, 10770],
          id: 89185,
          media_type: "movie",
          original_language: "en",
          original_title: "Radio Rebel",
          overview:
            "High school senior Tara is so painfully shy that she dreads speaking to anyone in the hallways or getting called on in class. But in the privacy of her bedroom with her iPod in hand, she rocks out -- doing mock broadcasts for Miami's hottest FM radio station, which happens to be owned by her stepfather. When a slot opens up at The SLAM, Tara surprises herself by blossoming behind the mike into confident, \"Radio Rebel\" -- and to everyone's shock, she's a hit!",
          poster_path: "/wycDdx2BrdNKlyTZoZT8uLeu6dq.jpg",
          release_date: "2012-06-09",
          title: "Radio Rebel",
          video: false,
          vote_average: 6.2,
          vote_count: 722,
        },
        {
          adult: false,
          backdrop_path: "/tz8D8e9yTv9Ki77BqyOL0tUSSsJ.jpg",
          genre_ids: [53, 12, 14],
          id: 45650,
          media_type: "movie",
          original_language: "en",
          original_title: "The Hole",
          overview:
            "After moving into a new neighbourhood, brothers Dane &amp; Lucas and their neighbour Julie discover a bottomless hole in the basement of their home. They find that once the hole is exposed, evil is unleashed. With strange shadows lurking around every corner and nightmares coming to life, they are forced to come face to face with their darkest fears to put an end to the mystery of THE HOLE.",
          poster_path: "/tQMxsrsVtpB2D2n01nUqgOMmSWD.jpg",
          release_date: "2009-09-09",
          title: "The Hole",
          video: false,
          vote_average: 5.7,
          vote_count: 586,
        },
      ],
      known_for_department: "Acting",
      name: "Merritt Patterson",
      popularity: 93.748,
      profile_path: "/JD4MNBtHjT2D43eUrBvNifhNpK.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 159962,
      known_for: [
        {
          backdrop_path: "/cJYLon9ejKJV7ua03ab8Tj9u067.jpg",
          first_air_date: "2009-09-10",
          genre_ids: [18, 10765],
          id: 18165,
          media_type: "tv",
          name: "The Vampire Diaries",
          origin_country: ["US"],
          original_language: "en",
          original_name: "The Vampire Diaries",
          overview:
            "The story of two vampire brothers obsessed with the same girl, who bears a striking resemblance to the beautiful but ruthless vampire they knew and loved in 1864.",
          poster_path: "/gbp4zM0FE0n23X4UFY5EBlacrog.jpg",
          vote_average: 8.3,
          vote_count: 6897,
        },
        {
          adult: false,
          backdrop_path: "/5iuae5Ji6WU0DrKPSMNz2MjCZfI.jpg",
          genre_ids: [35],
          id: 16996,
          media_type: "movie",
          original_language: "en",
          original_title: "17 Again",
          overview:
            "On the brink of a midlife crisis, 30-something Mike O'Donnell wishes he could have a \"do-over.\" And that's exactly what he gets when he wakes up one morning to find he's 17 years old again. With his adult mind stuck inside the body of a teenager, Mike actually has the chance to reverse some decisions he wishes he'd never made. But maybe they weren't so bad after all.",
          poster_path: "/wqE9b0bdZsubI82zdX1ykLfPajh.jpg",
          release_date: "2009-03-11",
          title: "17 Again",
          video: false,
          vote_average: 6.3,
          vote_count: 4207,
        },
        {
          adult: false,
          backdrop_path: "/mrYJ0ijgaxjHKAs0ybNYxyfP8l5.jpg",
          genre_ids: [35, 10751],
          id: 9820,
          media_type: "movie",
          original_language: "en",
          original_title: "The Parent Trap",
          overview:
            "Hallie Parker and Annie James are identical twins separated at a young age because of their parents' divorce. Unknowingly to their parents, the girls are sent to the same summer camp where they meet, discover the truth about themselves, and then plot with each other to switch places.",
          poster_path: "/a3XOGrrAjl1wwiumtACWBufg6AL.jpg",
          release_date: "1998-07-28",
          title: "The Parent Trap",
          video: false,
          vote_average: 7.1,
          vote_count: 3144,
        },
      ],
      known_for_department: "Acting",
      name: "Kat Graham",
      popularity: 91.374,
      profile_path: "/9AvpU8NAcPJRcioeNm5kVo4rPZg.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 71580,
      known_for: [
        {
          adult: false,
          backdrop_path: "/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
          genre_ids: [12, 28, 878],
          id: 299536,
          media_type: "movie",
          original_language: "en",
          original_title: "Avengers: Infinity War",
          overview:
            "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
          poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
          release_date: "2018-04-25",
          title: "Avengers: Infinity War",
          video: false,
          vote_average: 8.3,
          vote_count: 23710,
        },
        {
          adult: false,
          backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
          genre_ids: [12, 878, 28],
          id: 299534,
          media_type: "movie",
          original_language: "en",
          original_title: "Avengers: Endgame",
          overview:
            "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
          poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
          release_date: "2019-04-24",
          title: "Avengers: Endgame",
          video: false,
          vote_average: 8.3,
          vote_count: 20174,
        },
        {
          adult: false,
          backdrop_path: "/eQN31P4IEhyp6NkdccvppJnyuJ4.jpg",
          genre_ids: [28, 12, 14, 878],
          id: 284052,
          media_type: "movie",
          original_language: "en",
          original_title: "Doctor Strange",
          overview:
            "After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.",
          poster_path: "/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
          release_date: "2016-10-25",
          title: "Doctor Strange",
          video: false,
          vote_average: 7.4,
          vote_count: 18199,
        },
      ],
      known_for_department: "Acting",
      name: "Benedict Cumberbatch",
      popularity: 86.634,
      profile_path: "/fBEucxECxGLKVHBznO0qHtCGiMO.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 73968,
      known_for: [
        {
          adult: false,
          backdrop_path: "/mX3WOJPBzzl4kj4xU5lL7qfD6C3.jpg",
          genre_ids: [28, 12, 14],
          id: 209112,
          media_type: "movie",
          original_language: "en",
          original_title: "Batman v Superman: Dawn of Justice",
          overview:
            "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.",
          poster_path: "/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
          release_date: "2016-03-23",
          title: "Batman v Superman: Dawn of Justice",
          video: false,
          vote_average: 5.9,
          vote_count: 15470,
        },
        {
          adult: false,
          backdrop_path: "/69EFgWWPFWbRNHmQgYdSnyJ94Ge.jpg",
          genre_ids: [28, 12, 14, 878],
          id: 49521,
          media_type: "movie",
          original_language: "en",
          original_title: "Man of Steel",
          overview:
            "A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.",
          poster_path: "/8GFtkImmK0K1VaUChR0n9O61CFU.jpg",
          release_date: "2013-06-12",
          title: "Man of Steel",
          video: false,
          vote_average: 6.6,
          vote_count: 12801,
        },
        {
          adult: false,
          backdrop_path: "/jorgjEk6a0bed6jdR5wu4S6ZvRm.jpg",
          genre_ids: [28, 12, 14, 878],
          id: 141052,
          media_type: "movie",
          original_language: "en",
          original_title: "Justice League",
          overview:
            "Fuelled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne and Diana Prince assemble a team of metahumans consisting of Barry Allen, Arthur Curry and Victor Stone to face the catastrophic threat of Steppenwolf and the Parademons who are on the hunt for three Mother Boxes on Earth.",
          poster_path: "/eifGNCSDuxJeS1loAXil5bIGgvC.jpg",
          release_date: "2017-11-15",
          title: "Justice League",
          video: false,
          vote_average: 6.2,
          vote_count: 11077,
        },
      ],
      known_for_department: "Acting",
      name: "Henry Cavill",
      popularity: 85.695,
      profile_path: "/iWdKjMry5Pt7vmxU7bmOQsIUyHa.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 6614,
      known_for: [
        {
          adult: false,
          backdrop_path: "/bpV8wn48s82au37QyUJ51S7X2Vf.jpg",
          genre_ids: [18],
          id: 489,
          media_type: "movie",
          original_language: "en",
          original_title: "Good Will Hunting",
          overview:
            "Will Hunting has a genius-level IQ but chooses to work as a janitor at MIT. When he solves a difficult graduate-level math problem, his talents are discovered by Professor Gerald Lambeau, who decides to help the misguided youth reach his potential. When Will is arrested for attacking a police officer, Professor Lambeau makes a deal to get leniency for him if he will get treatment from therapist Sean Maguire.",
          poster_path: "/bABCBKYBK7A5G1x0FzoeoNfuj2.jpg",
          release_date: "1997-12-05",
          title: "Good Will Hunting",
          video: false,
          vote_average: 8.1,
          vote_count: 9289,
        },
        {
          adult: false,
          backdrop_path: "/z3ioibdjWZOYeXjoiabFOFOfPI3.jpg",
          genre_ids: [28, 80, 53],
          id: 584,
          media_type: "movie",
          original_language: "en",
          original_title: "2 Fast 2 Furious",
          overview:
            "It's a major double-cross when former police officer Brian O'Conner teams up with his ex-con buddy Roman Pearce to transport a shipment of \"dirty\" money for shady Miami-based import-export dealer Carter Verone. But the guys are actually working with undercover agent Monica Fuentes to bring Verone down.",
          poster_path: "/qC167IbZpSrwX7wWgg3BeDQbTDr.jpg",
          release_date: "2003-06-05",
          title: "2 Fast 2 Furious",
          video: false,
          vote_average: 6.4,
          vote_count: 5742,
        },
        {
          adult: false,
          backdrop_path: "/2ZusF7y230mM1NRlg9Ktgrak9Dg.jpg",
          genre_ids: [28, 53],
          id: 117263,
          media_type: "movie",
          original_language: "en",
          original_title: "Olympus Has Fallen",
          overview:
            'When the White House (Secret Service Code: "Olympus") is captured by a terrorist mastermind and the President is kidnapped, disgraced former Presidential guard Mike Banning finds himself trapped within the building. As the national security team scrambles to respond, they are forced to rely on Banning\'s inside knowledge to help retake the White House, save the President and avert an even bigger disaster.',
          poster_path: "/gKnx04MxnKcf5uOdhHhAAkqcCg.jpg",
          release_date: "2013-03-20",
          title: "Olympus Has Fallen",
          video: false,
          vote_average: 6.4,
          vote_count: 5556,
        },
      ],
      known_for_department: "Acting",
      name: "Cole Hauser",
      popularity: 79.235,
      profile_path: "/kJyUtNZREd7mes21OrWiCtOugPL.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 1172108,
      known_for: [
        {
          adult: false,
          backdrop_path: "/w2PMyoyLU22YvrGK3smVM9fW1jj.jpg",
          genre_ids: [28, 12, 878],
          id: 299537,
          media_type: "movie",
          original_language: "en",
          original_title: "Captain Marvel",
          overview:
            "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.",
          poster_path: "/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
          release_date: "2019-03-06",
          title: "Captain Marvel",
          video: false,
          vote_average: 6.9,
          vote_count: 12563,
        },
        {
          adult: false,
          backdrop_path: "/q7fXcrDPJcf6t3rzutaNwTzuKP1.jpg",
          genre_ids: [878, 12, 28],
          id: 333339,
          media_type: "movie",
          original_language: "en",
          original_title: "Ready Player One",
          overview:
            "When the creator of a popular video game system dies, a virtual contest is created to compete for his fortune.",
          poster_path: "/pU1ULUq8D3iRxl1fdX2lZIzdHuI.jpg",
          release_date: "2018-03-28",
          title: "Ready Player One",
          video: false,
          vote_average: 7.6,
          vote_count: 12464,
        },
        {
          adult: false,
          backdrop_path: "/ou70x2658dVnbycIRaC37sEeafS.jpg",
          genre_ids: [28, 12, 878],
          id: 47933,
          media_type: "movie",
          original_language: "en",
          original_title: "Independence Day: Resurgence",
          overview:
            "We always knew they were coming back. Using recovered alien technology, the nations of Earth have collaborated on an immense defense program to protect the planet. But nothing can prepare us for the aliens’ advanced and unprecedented force. Only the ingenuity of a few brave men and women can bring our world back from the brink of extinction.",
          poster_path: "/jzpvh0Ic7jL9GX4NLE1Tx2GUCrN.jpg",
          release_date: "2016-06-22",
          title: "Independence Day: Resurgence",
          video: false,
          vote_average: 5.2,
          vote_count: 5129,
        },
      ],
      known_for_department: "Acting",
      name: "Mckenna Grace",
      popularity: 78.839,
      profile_path: "/jQLBM6ErQnvU8QqNvW8KKF9y8N0.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 505710,
      known_for: [
        {
          adult: false,
          backdrop_path: "/tTlAA0REGPXSZPBfWyTW9ipIv1I.jpg",
          genre_ids: [28, 12, 878, 18],
          id: 315635,
          media_type: "movie",
          original_language: "en",
          original_title: "Spider-Man: Homecoming",
          overview:
            "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
          poster_path: "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
          release_date: "2017-07-05",
          title: "Spider-Man: Homecoming",
          video: false,
          vote_average: 7.4,
          vote_count: 17891,
        },
        {
          adult: false,
          backdrop_path: "/ng6SSB3JhbcpKTwbPDsRwUYK8Cq.jpg",
          genre_ids: [28, 12, 878],
          id: 429617,
          media_type: "movie",
          original_language: "en",
          original_title: "Spider-Man: Far From Home",
          overview:
            "Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
          poster_path: "/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
          release_date: "2019-06-28",
          title: "Spider-Man: Far From Home",
          video: false,
          vote_average: 7.5,
          vote_count: 11847,
        },
        {
          adult: false,
          backdrop_path: "/lrNKm3HNvGdZoAfiBKu7b04FLHN.jpg",
          genre_ids: [18],
          id: 316029,
          media_type: "movie",
          original_language: "en",
          original_title: "The Greatest Showman",
          overview:
            "The story of American showman P.T. Barnum, founder of the circus that became the famous traveling Ringling Bros. and Barnum & Bailey Circus.",
          poster_path: "/b9CeobiihCx1uG1tpw8hXmpi7nm.jpg",
          release_date: "2017-12-20",
          title: "The Greatest Showman",
          video: false,
          vote_average: 8,
          vote_count: 7896,
        },
      ],
      known_for_department: "Acting",
      name: "Zendaya",
      popularity: 78.701,
      profile_path: "/so3GqzuvXbYkNzQYNliAMB5rZzT.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 17521,
      known_for: [
        {
          adult: false,
          backdrop_path: "/oLmifRdaETboot2PXxpZN8NqHhK.jpg",
          genre_ids: [28, 12, 80, 9648],
          id: 10528,
          media_type: "movie",
          original_language: "en",
          original_title: "Sherlock Holmes",
          overview:
            "Eccentric consulting detective, Sherlock Holmes and Doctor John Watson battle to bring down a new nemesis and unravel a deadly plot that could destroy England.",
          poster_path: "/momkKuWburNTqKBF6ez7rvhYVhE.jpg",
          release_date: "2009-01-01",
          title: "Sherlock Holmes",
          video: false,
          vote_average: 7.2,
          vote_count: 11930,
        },
        {
          adult: false,
          backdrop_path: "/nVMalJRUsOeGP5xPx9ULmirZ4cJ.jpg",
          genre_ids: [12, 28, 80, 9648],
          id: 58574,
          media_type: "movie",
          original_language: "en",
          original_title: "Sherlock Holmes: A Game of Shadows",
          overview:
            "There is a new criminal mastermind at large (Professor Moriarty) and not only is he Holmes’ intellectual equal, but his capacity for evil and lack of conscience may give him an advantage over the  detective.",
          poster_path: "/y1MYZkwhZK6L0Jy4YMuPktzDOfn.jpg",
          release_date: "2011-11-22",
          title: "Sherlock Holmes: A Game of Shadows",
          video: false,
          vote_average: 7.1,
          vote_count: 8739,
        },
        {
          adult: false,
          backdrop_path: "/yBq4jWZLaEJIssuVx2fAysEwJnt.jpg",
          genre_ids: [18, 10749],
          id: 4348,
          media_type: "movie",
          original_language: "en",
          original_title: "Pride & Prejudice",
          overview:
            "A story of love and life among the landed English gentry during the Georgian era. Mr. Bennet is a gentleman living in Hertfordshire with his overbearing wife and five daughters, but if he dies their house will be inherited by a distant cousin whom they have never met, so the family's future happiness and security is dependent on the daughters making good marriages.",
          poster_path: "/sGjIvtVvTlWnia2zfJfHz81pZ9Q.jpg",
          release_date: "2005-09-16",
          title: "Pride & Prejudice",
          video: false,
          vote_average: 8.1,
          vote_count: 6256,
        },
      ],
      known_for_department: "Acting",
      name: "Kelly Reilly",
      popularity: 78.405,
      profile_path: "/l8aQsryOQvxgX6SdZ4XtzU8KEXn.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 963429,
      known_for: [
        {
          adult: false,
          backdrop_path: "/nM1kHUIalqE2cr3el1A06yKUlha.jpg",
          genre_ids: [16, 12, 35, 14],
          id: 223702,
          media_type: "movie",
          original_language: "en",
          original_title: "Sausage Party",
          overview:
            "Frank leads a group of supermarket products on a quest to discover the truth about their existence and what really happens when they become chosen to leave the grocery store.",
          poster_path: "/6jjOY2Vgii2wbUOYNWkMLLqnpZB.jpg",
          release_date: "2016-07-11",
          title: "Sausage Party",
          video: false,
          vote_average: 5.7,
          vote_count: 6052,
        },
        {
          adult: false,
          backdrop_path: "/lavWAUXVe7vHlKhZEGmfVLaVd4S.jpg",
          genre_ids: [35, 10749, 18],
          id: 4964,
          media_type: "movie",
          original_language: "en",
          original_title: "Knocked Up",
          overview:
            "For fun loving party animal Ben Stone, the last thing he ever expected was for his one night stand to show up on his doorstep eight weeks later to tell him she's pregnant.",
          poster_path: "/b4OaXw2MW97VvIiZE0Sbn1NfxSh.jpg",
          release_date: "2007-06-01",
          title: "Knocked Up",
          video: false,
          vote_average: 6.2,
          vote_count: 3206,
        },
        {
          adult: false,
          backdrop_path: "/botG6F4zvVD6WnDxQCWTU7U5cTD.jpg",
          genre_ids: [35],
          id: 89492,
          media_type: "movie",
          original_language: "en",
          original_title: "This Is 40",
          overview:
            "Pete and Debbie are both about to turn 40, their kids hate each other, both of their businesses are failing, they're on the verge of losing their house, and their relationship is threatening to fall apart.",
          poster_path: "/dtvOysDutHhlf862UP5X0w9h8Ju.jpg",
          release_date: "2012-12-20",
          title: "This Is 40",
          video: false,
          vote_average: 5.8,
          vote_count: 1776,
        },
      ],
      known_for_department: "Acting",
      name: "Iris Apatow",
      popularity: 77.507,
      profile_path: "/dVxJmLQf7XJl5GN9bY06gAYCtnL.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 37625,
      known_for: [
        {
          adult: false,
          backdrop_path: "/sLWUtbrpiLp23a0XDSiUiltdFPJ.jpg",
          genre_ids: [28, 12, 14],
          id: 1930,
          media_type: "movie",
          original_language: "en",
          original_title: "The Amazing Spider-Man",
          overview:
            "Peter Parker is an outcast high schooler abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben and Aunt May. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents' disappearance – leading him directly to Oscorp and the lab of Dr. Curt Connors, his father's former partner. As Spider-Man is set on a collision course with Connors' alter ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.",
          poster_path: "/fSbqPbqXa7ePo8bcnZYN9AHv6zA.jpg",
          release_date: "2012-06-23",
          title: "The Amazing Spider-Man",
          video: false,
          vote_average: 6.6,
          vote_count: 14330,
        },
        {
          adult: false,
          backdrop_path: "/u7SeO6Y42P7VCTWLhpnL96cyOqd.jpg",
          genre_ids: [28, 12, 14],
          id: 102382,
          media_type: "movie",
          original_language: "en",
          original_title: "The Amazing Spider-Man 2",
          overview:
            "For Peter Parker, life is busy. Between taking out the bad guys as Spider-Man and spending time with the person he loves, Gwen Stacy, high school graduation cannot come quickly enough. Peter has not forgotten about the promise he made to Gwen’s father to protect her by staying away, but that is a promise he cannot keep. Things will change for Peter when a new villain, Electro, emerges, an old friend, Harry Osborn, returns, and Peter uncovers new clues about his past.",
          poster_path: "/c3e9e18SSlvFd1cQaGmUj5tqL5P.jpg",
          release_date: "2014-04-16",
          title: "The Amazing Spider-Man 2",
          video: false,
          vote_average: 6.5,
          vote_count: 10538,
        },
        {
          adult: false,
          backdrop_path: "/yQIBS8B9l2qXoPoPtxSXvH7CfoT.jpg",
          genre_ids: [18, 36, 10752],
          id: 324786,
          media_type: "movie",
          original_language: "en",
          original_title: "Hacksaw Ridge",
          overview:
            "WWII American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first Conscientious Objector in American history to receive the Congressional Medal of Honor.",
          poster_path: "/fTuxNlgEm04PPFkr1xfK94Jn8BW.jpg",
          release_date: "2016-10-07",
          title: "Hacksaw Ridge",
          video: false,
          vote_average: 8.2,
          vote_count: 10464,
        },
      ],
      known_for_department: "Acting",
      name: "Andrew Garfield",
      popularity: 77.036,
      profile_path: "/beO5YvbTjrr5yy8hW26KVDMSr35.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 56734,
      known_for: [
        {
          adult: false,
          backdrop_path: "/zvRsjPHJDoJhhNdmYkFJqCdqmyr.jpg",
          genre_ids: [28, 80],
          id: 23483,
          media_type: "movie",
          original_language: "en",
          original_title: "Kick-Ass",
          overview:
            "Dave Lizewski is an unnoticed high school student and comic book fan who one day decides to become a super-hero, even though he has no powers, training or meaningful reason to do so.",
          poster_path: "/8citjdBmjddZjlPsAHEyCKwGVvD.jpg",
          release_date: "2010-03-22",
          title: "Kick-Ass",
          video: false,
          vote_average: 7.1,
          vote_count: 9869,
        },
        {
          adult: false,
          backdrop_path: "/etBZfuOie3uODTKTV5xnbAKB4Fr.jpg",
          genre_ids: [35, 18, 10749],
          id: 19913,
          media_type: "movie",
          original_language: "en",
          original_title: "(500) Days of Summer",
          overview:
            "Tom, greeting-card writer and hopeless romantic, is caught completely off-guard when his girlfriend, Summer, suddenly dumps him. He reflects on their 500 days together to try to figure out where their love affair went sour, and in doing so, Tom rediscovers his true passions in life.",
          poster_path: "/f9mbM0YMLpYemcWx6o2WeiYQLDP.jpg",
          release_date: "2009-07-17",
          title: "(500) Days of Summer",
          video: false,
          vote_average: 7.3,
          vote_count: 8116,
        },
        {
          adult: false,
          backdrop_path: "/gIjKKa0F4DOTub2CH8TwLe4tPOf.jpg",
          genre_ids: [53, 28, 80],
          id: 156022,
          media_type: "movie",
          original_language: "en",
          original_title: "The Equalizer",
          overview:
            "McCall believes he has put his mysterious past behind him and dedicated himself to beginning a new, quiet life. But when he meets Teri, a young girl under the control of ultra-violent Russian gangsters, he can’t stand idly by – he has to help her. Armed with hidden skills that allow him to serve vengeance against anyone who would brutalize the helpless, McCall comes out of his self-imposed retirement and finds his desire for justice reawakened. If someone has a problem, if the odds are stacked against them, if they have nowhere else to turn, McCall will help. He is The Equalizer.",
          poster_path: "/9u4yW7yPA0BQ2pv9XwiNzItwvp8.jpg",
          release_date: "2014-09-24",
          title: "The Equalizer",
          video: false,
          vote_average: 7.2,
          vote_count: 7015,
        },
      ],
      known_for_department: "Acting",
      name: "Chloë Grace Moretz",
      popularity: 75.17,
      profile_path: "/yq4rYmaTRC5degaOYmJQFpaiho1.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 976,
      known_for: [
        {
          adult: false,
          backdrop_path: "/mRfI3y2oAd7ejur2di09xC9niqp.jpg",
          genre_ids: [28, 53, 80],
          id: 82992,
          media_type: "movie",
          original_language: "en",
          original_title: "Fast & Furious 6",
          overview:
            "Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries: Dominic unexpectedly gets convoluted also facing his presumed deceased girlfriend, Letty.",
          poster_path: "/n31VRDodbaZxkrZmmzyYSFNVpW5.jpg",
          release_date: "2013-05-21",
          title: "Fast & Furious 6",
          video: false,
          vote_average: 6.8,
          vote_count: 9074,
        },
        {
          adult: false,
          backdrop_path: "/gyCHdpyPXmp7rqxE10nlImkzRo9.jpg",
          genre_ids: [28, 53, 80, 12],
          id: 168259,
          media_type: "movie",
          original_language: "en",
          original_title: "Furious 7",
          overview:
            "Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.",
          poster_path: "/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg",
          release_date: "2015-04-01",
          title: "Furious 7",
          video: false,
          vote_average: 7.3,
          vote_count: 8900,
        },
        {
          adult: false,
          backdrop_path: "/jzdnhRhG0dsuYorwvSqPqqnM1cV.jpg",
          genre_ids: [28, 80, 53],
          id: 337339,
          media_type: "movie",
          original_language: "en",
          original_title: "The Fate of the Furious",
          overview:
            "When a mysterious woman seduces Dom into the world of crime and a betrayal of those closest to him, the crew face trials that will test them as never before.",
          poster_path: "/dImWM7GJqryWJO9LHa3XQ8DD5NH.jpg",
          release_date: "2017-04-12",
          title: "The Fate of the Furious",
          video: false,
          vote_average: 6.9,
          vote_count: 8719,
        },
      ],
      known_for_department: "Acting",
      name: "Jason Statham",
      popularity: 73.928,
      profile_path: "/lldeQ91GwIVff43JBrpdbAAeYWj.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 1245,
      known_for: [
        {
          adult: false,
          backdrop_path: "/nNmJRkg8wWnRmzQDe2FwKbPIsJV.jpg",
          genre_ids: [878, 28, 12],
          id: 24428,
          media_type: "movie",
          original_language: "en",
          original_title: "The Avengers",
          overview:
            "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
          poster_path: "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
          release_date: "2012-04-25",
          title: "The Avengers",
          video: false,
          vote_average: 7.7,
          vote_count: 26209,
        },
        {
          adult: false,
          backdrop_path: "/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
          genre_ids: [12, 28, 878],
          id: 299536,
          media_type: "movie",
          original_language: "en",
          original_title: "Avengers: Infinity War",
          overview:
            "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
          poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
          release_date: "2018-04-25",
          title: "Avengers: Infinity War",
          video: false,
          vote_average: 8.3,
          vote_count: 23710,
        },
        {
          adult: false,
          backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
          genre_ids: [12, 878, 28],
          id: 299534,
          media_type: "movie",
          original_language: "en",
          original_title: "Avengers: Endgame",
          overview:
            "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
          poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
          release_date: "2019-04-24",
          title: "Avengers: Endgame",
          video: false,
          vote_average: 8.3,
          vote_count: 20174,
        },
      ],
      known_for_department: "Acting",
      name: "Scarlett Johansson",
      popularity: 72.604,
      profile_path: "/6NsMbJXRlDZuDzatN2akFdGuTvx.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 115150,
      known_for: [
        {
          adult: false,
          backdrop_path: "/udkrGMA9hsEGkQpmZ31rGpQQKp8.jpg",
          genre_ids: [28, 9648, 878, 53],
          id: 198663,
          media_type: "movie",
          original_language: "en",
          original_title: "The Maze Runner",
          overview:
            "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.",
          poster_path: "/ode14q7WtDugFDp78fo9lCsmay9.jpg",
          release_date: "2014-09-10",
          title: "The Maze Runner",
          video: false,
          vote_average: 7.2,
          vote_count: 14254,
        },
        {
          adult: false,
          backdrop_path: "/7C921eWK06n12c1miRXnYoEu5Yv.jpg",
          genre_ids: [12, 28, 14],
          id: 166426,
          media_type: "movie",
          original_language: "en",
          original_title: "Pirates of the Caribbean: Dead Men Tell No Tales",
          overview:
            "Thrust into an all-new adventure, a down-on-his-luck Capt. Jack Sparrow feels the winds of ill-fortune blowing even more strongly when deadly ghost sailors led by his old nemesis, the evil Capt. Salazar, escape from the Devil's Triangle. Jack's only hope of survival lies in seeking out the legendary Trident of Poseidon, but to find it, he must forge an uneasy alliance with a brilliant and beautiful astronomer and a headstrong young man in the British navy.",
          poster_path: "/qwoGfcg6YUS55nUweKGujHE54Wy.jpg",
          release_date: "2017-05-23",
          title: "Pirates of the Caribbean: Dead Men Tell No Tales",
          video: false,
          vote_average: 6.6,
          vote_count: 9838,
        },
        {
          adult: false,
          backdrop_path: "/4mcOCiR06dqQ5eoEJcG3zvonjOa.jpg",
          genre_ids: [878, 28, 53, 12],
          id: 294254,
          media_type: "movie",
          original_language: "en",
          original_title: "Maze Runner: The Scorch Trials",
          overview:
            "Thomas and his fellow Gladers face their greatest challenge yet: searching for clues about the mysterious and powerful organization known as WCKD. Their journey takes them to the Scorch, a desolate landscape filled with unimaginable obstacles. Teaming up with resistance fighters, the Gladers take on WCKD’s vastly superior forces and uncover its shocking plans for them all.",
          poster_path: "/mYw7ZyejqSCPFlrT2jHZOESZDU3.jpg",
          release_date: "2015-09-09",
          title: "Maze Runner: The Scorch Trials",
          video: false,
          vote_average: 6.7,
          vote_count: 8657,
        },
      ],
      known_for_department: "Acting",
      name: "Kaya Scodelario",
      popularity: 72.177,
      profile_path: "/oKsGrXKGrcVoQJQ6pbjZDPOQJcM.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 6384,
      known_for: [
        {
          adult: false,
          backdrop_path: "/ncEsesgOJDNrTUED89hYbA117wo.jpg",
          genre_ids: [28, 878],
          id: 603,
          media_type: "movie",
          original_language: "en",
          original_title: "The Matrix",
          overview:
            "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
          poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
          release_date: "1999-03-30",
          title: "The Matrix",
          video: false,
          vote_average: 8.2,
          vote_count: 20915,
        },
        {
          adult: false,
          backdrop_path: "/7dzngS8pLkGJpyeskCFcjPO9qLF.jpg",
          genre_ids: [28, 53],
          id: 245891,
          media_type: "movie",
          original_language: "en",
          original_title: "John Wick",
          overview:
            "Ex-hitman John Wick comes out of retirement to track down the gangsters that took everything from him.",
          poster_path: "/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
          release_date: "2014-10-22",
          title: "John Wick",
          video: false,
          vote_average: 7.4,
          vote_count: 15247,
        },
        {
          adult: false,
          backdrop_path: "/r17jFHAemzcWPPtoO0UxjIX0xas.jpg",
          genre_ids: [53, 28, 80],
          id: 324552,
          media_type: "movie",
          original_language: "en",
          original_title: "John Wick: Chapter 2",
          overview:
            "John Wick is forced out of retirement by a former associate looking to seize control of a shadowy international assassins’ guild. Bound by a blood oath to aid him, Wick travels to Rome and does battle against some of the world’s most dangerous killers.",
          poster_path: "/hXWBc0ioZP3cN4zCu6SN3YHXZVO.jpg",
          release_date: "2017-02-08",
          title: "John Wick: Chapter 2",
          video: false,
          vote_average: 7.3,
          vote_count: 9853,
        },
      ],
      known_for_department: "Acting",
      name: "Keanu Reeves",
      popularity: 71.185,
      profile_path: "/rRdru6REr9i3WIHv2mntpcgxnoY.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 17832,
      known_for: [
        {
          adult: false,
          backdrop_path: "/mX3WOJPBzzl4kj4xU5lL7qfD6C3.jpg",
          genre_ids: [28, 12, 14],
          id: 209112,
          media_type: "movie",
          original_language: "en",
          original_title: "Batman v Superman: Dawn of Justice",
          overview:
            "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.",
          poster_path: "/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
          release_date: "2016-03-23",
          title: "Batman v Superman: Dawn of Justice",
          video: false,
          vote_average: 5.9,
          vote_count: 15458,
        },
        {
          adult: false,
          backdrop_path: "/69EFgWWPFWbRNHmQgYdSnyJ94Ge.jpg",
          genre_ids: [28, 12, 14, 878],
          id: 49521,
          media_type: "movie",
          original_language: "en",
          original_title: "Man of Steel",
          overview:
            "A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.",
          poster_path: "/8GFtkImmK0K1VaUChR0n9O61CFU.jpg",
          release_date: "2013-06-12",
          title: "Man of Steel",
          video: false,
          vote_average: 6.6,
          vote_count: 12792,
        },
        {
          adult: false,
          backdrop_path: "/rwcPe582tfTSVLwQzbO25InW3Hi.jpg",
          genre_ids: [28, 12, 35, 10751, 14],
          id: 1593,
          media_type: "movie",
          original_language: "en",
          original_title: "Night at the Museum",
          overview:
            "Chaos reigns at the natural history museum when night watchman Larry Daley accidentally stirs up an ancient curse, awakening Attila the Hun, an army of gladiators, a Tyrannosaurus rex and other exhibits.",
          poster_path: "/uY9k8t2FQkMj60obnAnsPKLxHCE.jpg",
          release_date: "2006-10-20",
          title: "Night at the Museum",
          video: false,
          vote_average: 6.6,
          vote_count: 8396,
        },
      ],
      known_for_department: "Acting",
      name: "Carla Gugino",
      popularity: 69.11,
      profile_path: "/7lSH5LOexOHwvt9lOTsLTbXdU1G.jpg",
    },
  ],
  total_pages: 500,
  total_results: 10000,
}
