import { Country } from "~/configuration/countries"
import { Language } from "~/configuration/languages"

export interface PersonTvCredits {
  cast: PersonTvCredit[]
  crew: PersonTvCredit[]
  id: number
}

export interface PersonTvCredit {
  original_name: string
  id: number
  name: string
  vote_count: number
  vote_average: number
  first_air_date?: string
  poster_path: null | string
  genre_ids: number[]
  original_language: Language
  backdrop_path: null | string
  overview: string
  origin_country: Country[]
  popularity: number
  character?: string
  credit_id: string
  episode_count: number
  department?: string
  job?: string
}

export const mockPersonTvCredits: PersonTvCredits = {
  cast: [
    {
      original_name: "The One Show",
      id: 1514,
      name: "The One Show",
      vote_count: 14,
      vote_average: 4.7,
      first_air_date: "2006-08-14",
      poster_path: "/qCOlMsNSMDF5ZSvyzLJnFCqehkZ.jpg",
      genre_ids: [10763],
      original_language: "en",
      backdrop_path: "/1m3272Z1gOycFwJCM9hgFKfCiPZ.jpg",
      overview:
        "A topical magazine-style daily television programme broadcast live on BBC One and BBC One HD. The programme is currently hosted by Alex Jones and Matt Baker from Monday-Thursday, with Chris Evans appearing instead of Baker on Fridays and relief presenters appearing when required.",
      origin_country: ["GB"],
      popularity: 31.101,
      character: "Self - Guest",
      credit_id: "52570b0b760ee3776a061141",
      episode_count: 1,
    },
    {
      backdrop_path: "/nOJh6eAVjKmmD3W6Hb83k0zQgGb.jpg",
      first_air_date: "1987-04-05",
      genre_ids: [16, 35],
      id: 1679,
      name: "The Tracey Ullman Show",
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Tracey Ullman Show",
      overview:
        "The Tracey Ullman Show is an American television variety show, hosted by British-born comedian and onetime pop singer Tracey Ullman. It debuted on April 5, 1987 as the Fox network's second primetime series after Married... with Children, and ran until May 26, 1990. The show is produced by Gracie Films and 20th Century Fox Television. The show blended sketch comedy shorts with many musical numbers, featuring choreography by Paula Abdul. The show also produced The Simpsons shorts before it spun off into its own show, which was also produced by Gracie Films and 20th Century Fox Television.",
      poster_path: "/bxPSAqN8opsW4xXBHlgB2Jokjtc.jpg",
      vote_average: 7.1,
      vote_count: 14,
      popularity: 16.719,
      character: "Jesse Walker",
      credit_id: "5257103019c295711403ef2c",
      episode_count: 81,
    },
    {
      genre_ids: [10763, 10767],
      original_language: "en",
      poster_path: "/xlWdasY9oYg3OO5VTNqlPFftgya.jpg",
      vote_average: 5.8,
      original_name: "Today",
      origin_country: ["US"],
      vote_count: 17,
      overview:
        "Today is a daily American morning television show that airs on NBC. The program debuted on January 14, 1952. It was the first of its genre on American television and in the world, and is the fifth-longest running American television series. Originally a two-hour program on weekdays, it expanded to Sundays in 1987 and Saturdays in 1992. The weekday broadcast expanded to three hours in 2000, and to four hours in 2007.\n\nToday's dominance was virtually unchallenged by the other networks until the late 1980s, when it was overtaken by ABC's Good Morning America. Today retook the Nielsen ratings lead the week of December 11, 1995, and held onto that position for 852 consecutive weeks until the week of April 9, 2012, when it was beaten by Good Morning America yet again. In 2002, Today was ranked #17 on TV Guide's 50 Greatest Television  Shows of All Time.",
      id: 1709,
      backdrop_path: null,
      first_air_date: "1952-01-14",
      name: "Today",
      popularity: 5.278,
      character: "",
      credit_id: "525713f2760ee3776a1180c5",
      episode_count: 1,
    },
    {
      backdrop_path: "/uOPVhgfljgOM1SNz7eXuPHti9oK.jpg",
      first_air_date: "1988-09-05",
      genre_ids: [10767],
      id: 1900,
      name: "LIVE with Kelly and Ryan",
      origin_country: ["US"],
      original_language: "en",
      original_name: "LIVE with Kelly and Ryan",
      overview:
        "A morning talk show with A-list celebrity guests, top-notch performances and one-of-a-kind segments that are unrivaled on daytime television, plus spontaneous, hilarious and unpredictable talk.",
      poster_path: "/hBkyypWN3EcOzkozatiCm5VeaG.jpg",
      vote_average: 4.9,
      vote_count: 20,
      popularity: 259.228,
      character: "",
      credit_id: "52571a1e19c29571140c0ed8",
      episode_count: 1,
    },
    {
      backdrop_path: "/c5v6FCea3R0WG8u3qM5NvlfajxA.jpg",
      first_air_date: "1997-08-11",
      genre_ids: [10767],
      id: 2221,
      name: "The View",
      origin_country: ["US"],
      original_language: "en",
      original_name: "The View",
      overview:
        "ABC Daytime's morning chatfest, currently featuring Whoopi Goldberg, Joy Behar, Sunny Hostin, Meghan McCain, and Abby Huntsman, discussing the most exciting events of the day. Hot topics in the news, the best experts in their field, celebrity interviews and general entertainment are all part of The View.",
      poster_path: "/zn5ZtKXYo8XOoXUgtQxw7q2CjVt.jpg",
      vote_average: 4.8,
      vote_count: 69,
      popularity: 24.375,
      character: "Self",
      credit_id: "5257286a760ee3776a295152",
      episode_count: 2,
    },
    {
      original_name: "The Tonight Show with Jay Leno",
      id: 2518,
      name: "The Tonight Show with Jay Leno",
      vote_count: 60,
      vote_average: 5.4,
      first_air_date: "1992-05-25",
      poster_path: "/irA6aNsYCpN7Uo4EDQo8Fu6uzh7.jpg",
      genre_ids: [35, 10767],
      original_language: "en",
      backdrop_path: "/lN81B3YJ0cwnII3UJaHoIHwNN4J.jpg",
      overview:
        "The Tonight Show with Jay Leno is an American late-night talk show hosted by Jay Leno that initially aired from May 25, 1992 to May 29, 2009, and resumed production on March 1, 2010. The fourth incarnation of the Tonight Show franchise made its debut on May 25, 1992, three days following Johnny Carson's retirement as host of the program. The program originates from NBC Studios in Burbank, California, and is broadcast Monday through Friday at 11:35 PM in the Eastern and Pacific time zones. Unlike Carson or his predecessor Jack Paar, Leno only once utilized a guest host, preferring to host the series by himself.\n\nOn April 26, 1999, the show began broadcasting in 1080i HDTV, becoming the first American nightly talk show to be shot in high definition. The show is shot in 16:9 aspect ratio.\n\nThe series, which followed the same basic format as that of his predecessors, ran until May 29, 2009, after which Leno was succeeded by Conan O'Brien. NBC signed Leno to a new deal for a nightly talk show in the 10:00 pm ET timeslot. The primetime series, titled The Jay Leno Show, debuted on September 14, 2009, following a similar format to the Leno incarnation of Tonight.",
      origin_country: ["US"],
      popularity: 24.073,
      character: "",
      credit_id: "52573b56760ee36aaa01277b",
      episode_count: 4,
    },
    {
      backdrop_path: "/fxeKXn1k4AECuGQH6WjdRLq5saE.jpg",
      first_air_date: "1985-01-31",
      genre_ids: [80, 18],
      id: 3180,
      name: "Night Heat",
      origin_country: ["CA"],
      original_language: "en",
      original_name: "Night Heat",
      overview:
        "Night Heat is a Canadian police drama series\n\nThe show starred Allan Royal as journalist Tom Kirkwood, who chronicled the nightly police beat of detectives Kevin O'Brien and Frank Giambone.",
      poster_path: "/8T2JtoHcuHMq4CizFoDXq0eElkI.jpg",
      vote_average: 7.3,
      vote_count: 4,
      popularity: 8.301,
      character: "Thug #1",
      credit_id: "52574d9919c29531db0c8212",
      episode_count: 94,
    },
    {
      backdrop_path: "/fxeKXn1k4AECuGQH6WjdRLq5saE.jpg",
      first_air_date: "1985-01-31",
      genre_ids: [80, 18],
      id: 3180,
      name: "Night Heat",
      origin_country: ["CA"],
      original_language: "en",
      original_name: "Night Heat",
      overview:
        "Night Heat is a Canadian police drama series\n\nThe show starred Allan Royal as journalist Tom Kirkwood, who chronicled the nightly police beat of detectives Kevin O'Brien and Frank Giambone.",
      poster_path: "/8T2JtoHcuHMq4CizFoDXq0eElkI.jpg",
      vote_average: 7.3,
      vote_count: 4,
      popularity: 8.301,
      character: "Mugger",
      credit_id: "52574d9919c29531db0c81ac",
      episode_count: 94,
    },
    {
      backdrop_path: null,
      first_air_date: "2003-06-04",
      genre_ids: [10763, 99],
      id: 10946,
      name: "Celebrities Uncensored",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Celebrities Uncensored",
      overview:
        "Celebrities Uncensored is a TV program on the E! network that edited together amusing paparazzi footage of celebrities, usually in public places such as public sidewalks, restaurants, nightclubs, etc. The celebrities were often friendly, but sometimes their more unfriendly antics were featured in an amusing and entertaining way. It was very popular with stars on the rise and created a stir in the Hollywood community. Paris Hilton was first brought to the public's attention by this show.",
      poster_path: null,
      vote_average: 2.5,
      vote_count: 4,
      popularity: 0.6,
      character: "",
      credit_id: "5258094a19c29531db3e3065",
      episode_count: 2,
    },
    {
      backdrop_path: null,
      first_air_date: "1981-01-07",
      genre_ids: [],
      id: 14920,
      name: "Hangin' In",
      origin_country: ["CA"],
      original_language: "en",
      original_name: "Hangin' In",
      overview:
        "Hangin' In is a Canadian television sitcom which aired on CBC from 1981 to 1987. It also aired briefly in syndication in the United States. Canadian producer Jack Humphrey developed Hangin' In and served as executive producer for the show.",
      poster_path: "/1wl1ws2YPdhAgolASx2gPeJZW2N.jpg",
      vote_average: 0.0,
      vote_count: 0,
      popularity: 2.131,
      character: "Teen Client",
      credit_id: "52583668760ee36aaa942886",
      episode_count: 8,
    },
    {
      backdrop_path: "/xXw353pKdfJ8ikYzH4FHAErCHNK.jpg",
      first_air_date: "1953-03-18",
      genre_ids: [],
      id: 27023,
      name: "The Oscars",
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Oscars",
      overview:
        "An annual American awards ceremony honoring cinematic achievements in the film industry. The various category winners are awarded a copy of a statuette, officially the Academy Award of Merit, that is better known by its nickname Oscar.",
      poster_path: "/8BjJPRw1fbfgvUsdm0F82bSDiXh.jpg",
      vote_average: 6.9,
      vote_count: 51,
      popularity: 9.951,
      character: "Self",
      credit_id: "52588339760ee34661403f9e",
      episode_count: 5,
    },
    {
      backdrop_path: null,
      first_air_date: "1985-06-28",
      genre_ids: [],
      id: 30240,
      name: "Comedy Factory",
      origin_country: ["CA"],
      original_language: "en",
      original_name: "Comedy Factory",
      overview: "",
      poster_path: null,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 0.84,
      character: "Crackers",
      credit_id: "525896f4760ee346615a8dcb",
      episode_count: 1,
    },
    {
      original_name: "Easy to Assemble",
      id: 34441,
      name: "Easy to Assemble",
      vote_count: 1,
      vote_average: 5.0,
      first_air_date: "2008-09-22",
      poster_path: "/amfW7NzijzI7Kj27Od4yCRzNSAq.jpg",
      genre_ids: [35],
      original_language: "en",
      backdrop_path: null,
      overview:
        'Easy to Assemble is a Webseries created by and starring Illeana Douglas, and sponsored by furniture store IKEA.\n\nDouglas plays a fictional version of herself trying to quit acting and work a "real job" at the IKEA in Burbank, CA. She soon finds she cannot leave Hollywood behind when fellow actress Justine Bateman starts an internet talk show called "40 and Bitter" on the floor of IKEA.\n\nThe series has had several notable guest stars, including Jeff Goldblum, Keanu Reeves, Jane Lynch, Justine Bateman, Tim Meadows, Cheri Oteri, Tom Arnold, Ed Begley, Jr., Kevin Pollak, Fred Willard, Daryl Sabara, Ricki Lake, David Henrie, Patricia Heaton, and Eric Lange.',
      origin_country: ["US"],
      popularity: 6.525,
      character: "Vorste Feirron",
      credit_id: "5258d89c760ee34661719de4",
      episode_count: 51,
    },
    {
      backdrop_path: "/At7XQ83krOAmiLMPSkBAK07XERi.jpg",
      first_air_date: "2003-01-26",
      genre_ids: [10767, 35],
      id: 1489,
      name: "Jimmy Kimmel Live!",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Jimmy Kimmel Live!",
      overview:
        "Jimmy Kimmel Live! is an American late-night talk show, created and hosted by Jimmy Kimmel and broadcast on ABC.",
      poster_path: "/pUTTBIUO4U5rZjYcZ3Lk51vHr20.jpg",
      vote_average: 5.6,
      vote_count: 99,
      popularity: 30.209,
      character: "",
      credit_id: "525707d8760ee3776a03889f",
      episode_count: 1,
    },
    {
      backdrop_path: "/qIA7VqJijSCY4afQXE7Uv0EEYWg.jpg",
      first_air_date: "1996-03-29",
      genre_ids: [18, 99],
      id: 3739,
      name: "E! True Hollywood Story",
      origin_country: ["US"],
      original_language: "en",
      original_name: "E! True Hollywood Story",
      overview:
        'E! True Hollywood Story is an American documentary series on E! that deals with famous Hollywood celebrities, movies, TV shows and also well-known public figures. Among the topics covered on the program include salacious re-tellings of Hollywood secrets, show-biz scandals, celebrity murders and mysteries, porn-star biographies, and "where-are-they-now?" investigations of former child stars. It frequently features in-depth interviews, actual courtroom footage, and dramatic reenactments. When aired on the E! network, episodes will be updated to reflect the current life or status of the subject.',
      poster_path: "/zuXXivVEjOkMswJvNFFRmJW0bTZ.jpg",
      vote_average: 9.5,
      vote_count: 50,
      popularity: 1.303,
      character: "",
      credit_id: "525755c119c29531db1373eb",
      episode_count: 1,
    },
    {
      backdrop_path: "/wbwBw3cJN4HohKRW6eq3bfw2Hwe.jpg",
      first_air_date: "1995-10-14",
      genre_ids: [35],
      id: 4469,
      name: "MADtv",
      origin_country: ["US"],
      original_language: "en",
      original_name: "MADtv",
      overview:
        "MADtv is an American sketch comedy television series originally inspired by Mad magazine. The one-hour show aired Saturday nights on Fox.",
      poster_path: "/xBhqJk2Uvn3XzQxKnq96ESwDYES.jpg",
      vote_average: 6.8,
      vote_count: 77,
      popularity: 1.77,
      character: "",
      credit_id: "52576b20760ee36aaa3e71d1",
      episode_count: 1,
    },
    {
      first_air_date: "2005-01-09",
      vote_average: 10.0,
      id: 15025,
      overview:
        "Unscripted is an American comedy-drama series that aired on HBO in early 2005. Its title referred to the fact that the series was largely improvised by its performers. The series was executive produced by Steven Soderbergh, George Clooney, and Grant Heslov.",
      name: "Unscripted",
      backdrop_path: "/gXg7oDMIa4y4OKTsd1FSf1WIPBr.jpg",
      original_name: "Unscripted",
      origin_country: ["US"],
      original_language: "en",
      vote_count: 1,
      poster_path: "/7Pl4nmauF6M9lbH3cssYMUQsToC.jpg",
      genre_ids: [18, 35],
      popularity: 4.643,
      character: "Himself",
      credit_id: "5258376f760ee36aaa95a0db",
      episode_count: 1,
    },
    {
      original_name: "Bill & Ted's Excellent Adventures",
      backdrop_path: "/hvLjMoZ9StBSeSYPAZBlrwU0ifR.jpg",
      id: 35006,
      name: "Bill & Ted's Excellent Adventures",
      original_language: "en",
      poster_path: "/6JhwrUjk905wmhp7s7B0UeuyOma.jpg",
      vote_average: 6.7,
      vote_count: 12,
      overview:
        "The misadventures of two time-travelling slackers as they travel into the distant past and future.",
      first_air_date: "1990-09-15",
      genre_ids: [16, 35],
      origin_country: ["US"],
      popularity: 4.802,
      character: "Ted Logan (voice)",
      credit_id: "5258dc30760ee3466175a784",
      episode_count: 13,
    },
    {
      first_air_date: "2007-02-22",
      genre_ids: [35, 10767],
      original_language: "en",
      poster_path: "/vrbqaBXB8AALynQzpWz6JdCPEJS.jpg",
      name: "The Graham Norton Show",
      original_name: "The Graham Norton Show",
      origin_country: ["GB"],
      vote_average: 7.2,
      vote_count: 184,
      overview:
        "Each week celebrity guests join Irish comedian Graham Norton to discuss what's being going on around the world that week. The guests poke fun and share their opinions on the main news stories. Graham is often joined by a band or artist to play the show out.",
      backdrop_path: "/2pJYis3LUEgFC3UErTQVgmUV1hN.jpg",
      id: 1220,
      popularity: 113.863,
      character: "Self",
      credit_id: "588c560992514137c3003789",
      episode_count: 4,
    },
    {
      name: "Mundo VIP",
      original_language: "pt",
      poster_path: null,
      vote_average: 0.0,
      overview: "",
      original_name: "Mundo VIP",
      origin_country: ["PT"],
      id: 35491,
      vote_count: 0,
      backdrop_path: null,
      genre_ids: [10766],
      first_air_date: "1996-04-21",
      popularity: 4.434,
      character: "Himself",
      credit_id: "5bc0836d0e0a266e640168b0",
      episode_count: 1,
    },
    {
      backdrop_path: null,
      first_air_date: "1948-01-01",
      genre_ids: [10764],
      id: 89293,
      name: "Bambi Awards",
      origin_country: ["DE"],
      original_language: "de",
      original_name: "Bambi-Verleihung",
      overview:
        "The Bambi, often called the Bambi Award and stylised as BAMBI, is a German award presented annually by Hubert Burda Media to recognize excellence in international media and television to personalities in the media, arts, culture, sports, and other fields \"with vision and creativity who affected and inspired the German public that year\", both domestic and foreign. First held in 1948, it is the oldest media award in Germany. The trophy is named after Felix Salten's book Bambi, A Life in the Woods and its statuettes are in the shape of the novel's titular fawn character. They were originally made of porcelain until 1958, when the organizers switched to using gold, with the casting done by the art casting workshop of Ernst Strassacker in Süßen.",
      poster_path: "/7Bc1fE5mKIYmhhgl0fVcw3nvDra.jpg",
      vote_average: 0.0,
      vote_count: 0,
      popularity: 15.391,
      character: "Self",
      credit_id: "5cd8790dc3a36831dec1e57d",
      episode_count: 1,
    },
    {
      backdrop_path: null,
      first_air_date: "",
      genre_ids: [],
      id: 90169,
      name: "Rain",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Rain",
      overview:
        "An assassin specializes in making his hits look like they've died from natural causes.",
      poster_path: null,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 2.304,
      character: "John Rain",
      credit_id: "5cfe4e22c3a36804ae1fd2e9",
      episode_count: 1,
    },
    {
      genre_ids: [10767],
      original_language: "fr",
      poster_path: "/o4JQcem2uszT5vwrOkQUn1zZ3LH.jpg",
      vote_count: 3,
      vote_average: 9.3,
      id: 73347,
      overview:
        "Patrice Bélanger and his team are here to give Quebecers a little boost to their lives with this show where fun and pleasure prevail. With a front row seat to events happening across the province, the show is the reference for summer culture. Above and beyond the artists featured, the show puts our entire province in the spotlight.",
      first_air_date: "2002-06-03",
      original_name: "Sucré Salé",
      origin_country: ["CA"],
      name: "Sucré Salé",
      backdrop_path: "/pWTP8mJ6mQgfRUlsGmLlKkVISIP.jpg",
      popularity: 2.579,
      character: "Self",
      credit_id: "5cff055dc3a3680cac201494",
      episode_count: 1,
    },
    {
      backdrop_path: "/7RizgNN3qH1vjDbhWrJKFoxPfrT.jpg",
      genre_ids: [99, 10765],
      original_language: "en",
      poster_path: "/qhanotOZnOdgmCZonug5anT0mFo.jpg",
      id: 79003,
      vote_count: 27,
      first_air_date: "2018-04-29",
      vote_average: 6.3,
      overview:
        "Explore the evolution of sci-fi from its origins as a small genre with a cult following to the blockbuster pop-cultural phenomenon we know today. In each episode, James Cameron introduces one of the “Big Questions” that humankind has contemplated throughout the ages and reaches back into sci-fi’s past to better understand how our favorite films, TV shows, books, and video games were born.",
      name: "James Cameron's Story of Science Fiction",
      original_name: "James Cameron's Story of Science Fiction",
      origin_country: ["US"],
      popularity: 10.615,
      character: "Self",
      credit_id: "5d259772a698cf0010ab7e23",
      episode_count: 2,
    },
    {
      id: 64229,
      poster_path: "/h4T23oAVxLky9YDpV3wp6qdnkjz.jpg",
      name: "Jay Leno's Garage",
      original_name: "Jay Leno's Garage",
      origin_country: ["US"],
      overview:
        "Comedian and former Tonight Show host Jay Leno shares his passion for motor vehicles. Jay and guests drive cars, motorbikes and anything that moves all while meeting new people and exploring the rich motoring history of America and beyond.",
      vote_count: 7,
      backdrop_path: "/Pp5z78uD9KLHtO4l7Bhx22HJ7c.jpg",
      vote_average: 6.9,
      genre_ids: [10764, 99],
      first_air_date: "2015-10-07",
      original_language: "en",
      popularity: 10.584,
      character: "Himself",
      credit_id: "5dcfbcae2866fa001886a40e",
      episode_count: 1,
    },
    {
      backdrop_path: "/i0UCVVewgm9reBYGBVgAVArSsY3.jpg",
      first_air_date: "2014-10-14",
      genre_ids: [10764],
      id: 95390,
      name: "Car Matchmaker with Spike Feresten",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Car Matchmaker with Spike Feresten",
      overview:
        "TV writer, talk show host and comedian, Spike Feresten, is the guy to see when car shopping. He meets someone needing a car and then draws on two decades of expertise and instinct to find three different cars perfectly suited to the buyer.",
      poster_path: "/iWvX5oWzzFzjzDdUPBo7Z0NDp8L.jpg",
      vote_average: 0.0,
      vote_count: 0,
      popularity: 2.17,
      character: "Himself",
      credit_id: "5dcf8aebb76cbb001178446e",
      episode_count: 1,
    },
    {
      backdrop_path: "/JiRMfGJQNpQUzVkA6bk36B5cq0.jpg",
      first_air_date: "2020-10-01",
      genre_ids: [99],
      id: 106081,
      name: "A World of Calm",
      origin_country: ["US"],
      original_language: "en",
      original_name: "A World of Calm",
      overview:
        "A timely antidote for our modern lives, this revolutionary series takes audiences on an immersive audiovisual journey designed to help you relax and transform how you feel. Each episode is brought to life by narration from some of the smoothest voices in Hollywood.",
      poster_path: "/mAHwKoRDxL0ZeNdTIBBrzbVYcaA.jpg",
      vote_average: 6.3,
      vote_count: 3,
      popularity: 6.908,
      character: "Narrator",
      credit_id: "5f7fdd0a2f3b170037f44b25",
      episode_count: 1,
    },
    {
      backdrop_path: "/i4Dy5GyA9IoXVoYOqRXm2kkQDu3.jpg",
      first_air_date: "2016-09-02",
      genre_ids: [35, 80],
      id: 67642,
      name: "Swedish Dicks",
      origin_country: ["SE"],
      original_language: "en",
      original_name: "Swedish Dicks",
      overview:
        "Two unlicensed Swedish private investigators try to make a living in Los Angeles.",
      poster_path: "/hn04dMzVCcZuwLV8otfj1brqHVQ.jpg",
      vote_average: 6.7,
      vote_count: 19,
      popularity: 10.943,
      character: "Tex Johnson",
      credit_id: "5f8056e32667780037b1fa5e",
      episode_count: 13,
    },
    {
      original_name: "HBO First Look",
      id: 33833,
      name: "HBO First Look",
      vote_count: 7,
      vote_average: 5.0,
      first_air_date: "1992-06-12",
      poster_path: null,
      genre_ids: [99],
      original_language: "en",
      backdrop_path: null,
      overview:
        "HBO First Look is an American television show on HBO that chronicles up and coming movies. It first started in 1992 with a documentary on A League of Their Own starring Tom Hanks, and still airs today. The series shows behind-the-scenes looks at the filming and interviews with the actors. The show is part documentary and part advertisement. It airs on HBO with no set schedule.",
      origin_country: ["US"],
      popularity: 10.145,
      character: "",
      credit_id: "5f9b647d5f2db1003a1f0418",
      episode_count: 1,
    },
    {
      backdrop_path: null,
      first_air_date: "",
      genre_ids: [],
      id: 19041,
      name: "Conquest",
      origin_country: [],
      original_language: "en",
      original_name: "Conquest",
      overview: "",
      poster_path: null,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 1.34,
      character: "",
      credit_id: "5fc55984a8858700420a5125",
      episode_count: 1,
    },
    {
      genre_ids: [10763, 10767],
      original_language: "de",
      first_air_date: "1997-03-11",
      poster_path: null,
      vote_count: 1,
      name: "Taff",
      original_name: "Taff",
      origin_country: ["DE"],
      vote_average: 1.0,
      overview:
        "Taff is a tabloid news magazine airing on the German television network, ProSieben.",
      backdrop_path: null,
      id: 42265,
      popularity: 12.618,
      character: "self",
      credit_id: "5fd6246ec8a5ac0041f9baae",
      episode_count: 1,
    },
    {
      backdrop_path: "/6jGVOu5NvnmSKh28ByWAJrTOEH2.jpg",
      first_air_date: "2014-02-17",
      genre_ids: [35, 10767],
      id: 59941,
      name: "The Tonight Show Starring Jimmy Fallon",
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Tonight Show Starring Jimmy Fallon",
      overview:
        "After Jay Leno's second retirement from the program, Jimmy Fallon stepped in as his permanent replacement. After 42 years in Los Angeles the program was brought back to New York.",
      poster_path: "/if7ECoH4xaYw5S8gomNIEmtwTxP.jpg",
      vote_average: 6.1,
      vote_count: 171,
      popularity: 76.971,
      character: "Self",
      credit_id: "5fe6816d1d6c5f003fe02dbf",
      episode_count: 1,
    },
    {
      backdrop_path: null,
      first_air_date: "",
      genre_ids: [16, 10759, 10765],
      id: 121505,
      name: "BRZRKR",
      origin_country: [],
      original_language: "en",
      original_name: "BRZRKR",
      overview:
        "A brutally epic saga about an immortal warrior's 80,000 year fight through the ages.",
      poster_path: null,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 0.84,
      character: "B (voice)",
      credit_id: "6059a3bed371970076801f5a",
      episode_count: 1,
    },
    {
      backdrop_path: "/uOPVhgfljgOM1SNz7eXuPHti9oK.jpg",
      first_air_date: "1988-09-05",
      genre_ids: [10767],
      id: 1900,
      name: "LIVE with Kelly and Ryan",
      origin_country: ["US"],
      original_language: "en",
      original_name: "LIVE with Kelly and Ryan",
      overview:
        "A morning talk show with A-list celebrity guests, top-notch performances and one-of-a-kind segments that are unrivaled on daytime television, plus spontaneous, hilarious and unpredictable talk.",
      poster_path: "/hBkyypWN3EcOzkozatiCm5VeaG.jpg",
      vote_average: 4.9,
      vote_count: 20,
      popularity: 259.228,
      character: "Self - Guest",
      credit_id: "61b3282938e5100061408298",
      episode_count: 1,
    },
    {
      backdrop_path: "/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg",
      first_air_date: "2015-09-08",
      genre_ids: [35, 10767],
      id: 63770,
      name: "The Late Show with Stephen Colbert",
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Late Show with Stephen Colbert",
      overview:
        'Improv actor and comic Stephen Colbert leaves his "The Colbert Report" character behind as he makes his long-awaited return to television. As the host of The Late Show franchise redux - taped at the historic Ed Sullivan Theatre at New York - Colbert talks to actors, athletes, politicians, comics, artists and musicians as himself for the first time. Loyal fans, however, will also be treated to consistency as Colbert remains backed by many members of his writing and digital team from his former venture. Julliard-trained Jon Batiste serves as the bandleader.',
      poster_path: "/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg",
      vote_average: 6.5,
      vote_count: 153,
      popularity: 127.451,
      character: "",
      credit_id: "61b87095873f000042b4d788",
      episode_count: 3,
    },
    {
      overview:
        "An architect works to build up the 1893 World's Fair, while the serial killer H. H. Holmes uses the fair to attract and kill women.",
      id: 138566,
      original_name: "The Devil in the White City",
      backdrop_path: null,
      genre_ids: [18, 80, 9648],
      name: "The Devil in the White City",
      original_language: "en",
      poster_path: null,
      vote_count: 0,
      vote_average: 0.0,
      origin_country: ["US"],
      popularity: 1.751,
      character: "Dr. H. H. Holmes",
      credit_id: "61d4083f944a57001f8e0f36",
      episode_count: 1,
    },
    {
      backdrop_path: "/8Zm2LR8YmGMF67Oofc9FdBSw1WM.jpg",
      genre_ids: [10767],
      original_name: "Red Table Talk",
      origin_country: ["US"],
      poster_path: "/9MFH6LriSscCg9HiGeLam78KfBV.jpg",
      name: "Red Table Talk",
      first_air_date: "2018-05-07",
      vote_average: 7.3,
      vote_count: 4,
      overview:
        "Jada Pinkett Smith, her daughter Willow, and mother Adrienne – three generations of women open their home for a series of candid conversations with family and friends.",
      original_language: "en",
      id: 83216,
      popularity: 6.719,
      character: "Self",
      credit_id: "61db4fd9d7f465001cd00337",
      episode_count: 1,
    },
    {
      backdrop_path: "/iu2GYGDglHEv1gYiwwwx3MA2Evt.jpg",
      genre_ids: [10767],
      original_language: "en",
      poster_path: "/fpcYoqpnTmYm84sXcjXvrs7VtTz.jpg",
      first_air_date: "2020-09-14",
      vote_average: 0.0,
      original_name: "The Drew Barrymore Show",
      origin_country: ["US"],
      vote_count: 0,
      overview:
        "Drew Barrymore presents human-interest stories, celebrity guests, lifestyle segments and field pieces, all driven by her infectious brand of humor and optimism.",
      id: 108178,
      name: "The Drew Barrymore Show",
      popularity: 7.445,
      character: "Self",
      credit_id: "623c94046f43ec005c9d283c",
      episode_count: 1,
    },
  ],
  crew: [
    {
      backdrop_path: null,
      first_air_date: "",
      genre_ids: [],
      id: 90169,
      name: "Rain",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Rain",
      overview:
        "An assassin specializes in making his hits look like they've died from natural causes.",
      poster_path: null,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 2.304,
      credit_id: "5cfe4dc70e0a261f29ca6d61",
      department: "Production",
      episode_count: 1,
      job: "Executive Producer",
    },
  ],
  id: 6384,
}
